<a href="https://colab.research.google.com/github/collinscolour/GoMyCodeCheckPoint/blob/main/Supportvectormachines_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this checkpoint, we are going to work on the 'Electric Vehicle Data' dataset that was provided by Kaggle as part of the Electric Vehicle Price Prediction competition.

Dataset description: This dataset contains information on the Battery Electric Vehicles (BEVs) and Plug-in Hybrid Electric Vehicles (PHEVs) that are currently registered with the Washington State Department of Licensing (DOL). This dataset was introduced as part of an official invitation-based competition on Kaggle. Our SVM model should answer the question "This is my car's model & make, along with a few other parameters, what price can this vehicle be brought or sold?”

➡️ Dataset link


➡️Columns explanation



Instructions
Import you data and perform basic data exploration phase

Display general information about the dataset

Create a pandas profiling reports to gain insights into the dataset

Handle Missing and corrupted values

Remove duplicates, if they exist

Handle outliers, if they exist

Encode categorical features

Select your target variable and the features

Split your dataset to training and test sets

Build and train an SVM model on the training set

Assess your model performance on the test set using relevant' evaluation metrics
Discuss with your cohort alternative ways to improve your model performance

In [19]:
#import
import pandas as pd
from ydata_profiling import ProfileReport
from scipy import stats
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [3]:
data = pd.read_csv("Electric_cars_dataset.csv")
print(data.head())

        ID  VIN (1-10)     County        City State  ZIP Code  Model Year  \
0  EV33174  5YJ3E1EC6L  Snohomish    LYNNWOOD    WA   98037.0      2020.0   
1  EV40247  JN1AZ0CP8B     Skagit  BELLINGHAM    WA   98229.0      2011.0   
2  EV12248  WBY1Z2C56F     Pierce      TACOMA    WA   98422.0      2015.0   
3  EV55713  1G1RD6E44D       King     REDMOND    WA   98053.0      2013.0   
4  EV28799  1G1FY6S05K     Pierce    PUYALLUP    WA   98375.0      2019.0   

        Make    Model                   Electric Vehicle Type  \
0      TESLA  MODEL 3          Battery Electric Vehicle (BEV)   
1     NISSAN     LEAF          Battery Electric Vehicle (BEV)   
2        BMW       I3          Battery Electric Vehicle (BEV)   
3  CHEVROLET     VOLT  Plug-in Hybrid Electric Vehicle (PHEV)   
4  CHEVROLET  BOLT EV          Battery Electric Vehicle (BEV)   

  Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0           Clean Alternative Fuel Vehicle Eligible             308   
1   

In [4]:
# Clean the data
# Check for missing values
data.isnull().sum()

ID                                                     0
VIN (1-10)                                             0
County                                                 4
City                                                   9
State                                                 11
ZIP Code                                               6
Model Year                                             7
Make                                                   4
Model                                                 13
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 169
DOL Vehicle ID                                         0
Vehicle Location                                     510
Electric Utility                                     722
Expected Price ($1k)           

In [5]:
# drop all missing values
data.dropna(inplace=True)

In [6]:
#recheck for missing values
data.isnull().sum()

ID                                                   0
VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
ZIP Code                                             0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Base MSRP                                            0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     0
Expected Price ($1k)                                 0
dtype: int

In [7]:
# check for duplicate values
data.duplicated().sum()

0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63081 entries, 0 to 64352
Data columns (total 18 columns):
 #   Column                                             Non-Null Count  Dtype  
---  ------                                             --------------  -----  
 0   ID                                                 63081 non-null  object 
 1   VIN (1-10)                                         63081 non-null  object 
 2   County                                             63081 non-null  object 
 3   City                                               63081 non-null  object 
 4   State                                              63081 non-null  object 
 5   ZIP Code                                           63081 non-null  float64
 6   Model Year                                         63081 non-null  float64
 7   Make                                               63081 non-null  object 
 8   Model                                              63081 non-null  object 
 9   Electr

In [9]:
data.describe()

ZIP Code    Model Year  Electric Range      Base MSRP  \
count  63081.000000  63081.000000    63081.000000   63081.000000   
mean   98252.381827   2018.187109      107.088569    2529.523866   
std      330.715600      2.725192      104.111828   12431.057011   
min    59937.000000   1993.000000        0.000000       0.000000   
25%    98052.000000   2017.000000       14.000000       0.000000   
50%    98119.000000   2018.000000       73.000000       0.000000   
75%    98368.000000   2021.000000      215.000000       0.000000   
max    99403.000000   2022.000000      337.000000  845000.000000   

       Legislative District  DOL Vehicle ID  
count          63081.000000    6.308100e+04  
mean              30.060383    1.973738e+08  
std               14.665353    1.070546e+08  
min                0.000000    4.385000e+03  
25%               20.000000    1.373311e+08  
50%               34.000000    1.754003e+08  
75%               43.000000    2.300375e+08  
max               49.000000    4.789346e+08

In [10]:
!pip install ydata_profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.6/357.6 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 32.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 kB 40.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 26.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 65.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 62.1 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=cb6c341fe3685f66e09612cab8836935bb7d4cad38c6c11e73853c0595dc9e30
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
 

In [10]:
# Generate the profiling report
profile = ProfileReport(data)

# Save the report to HTML
profile.to_file('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
data=data[(np.abs(stats.zscore(data["Electric Range"]))<3)]

In [15]:
#encoding categorical features using LabelEncoder
categorical_features = data.select_dtypes(include=['object', 'category']).columns
for feature in categorical_features:
  encoder = LabelEncoder()
  data[feature] = encoder.fit_transform(data[feature])

In [20]:
#Split your dataset to training and test sets
target_variable = 'Expected Price ($1k)'
feature_variables = ["County"]
y= data[target_variable]
X= data[feature_variables].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [21]:
svm_model = SVC()
svm_model.fit(X_train, y_train)

SVC()

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(X_train, y_train)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 2 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

True Positives(TP) =  0

True Negatives(TN) =  0

False Positives(FP) =  1

False Negatives(FN) =  0
